Repository vim-ctrlspace/vim-ctrlspace, pull requests merged in 2020-03, with the labels that each got.

#257 README & docs/ctrlspace.txt updates to copyright years, timespan, etc.
  CHANGELOG.md
  README.md
  autoload/ctrlspace/help.vim
  doc/ctrlspace.txt
Labels: docs

#254 make system calls independent of shell setting
  autoload/ctrlspace/context.vim
  autoload/ctrlspace/engine.vim
  autoload/ctrlspace/files.vim
  autoload/ctrlspace/util.vim
Labels: bug, fixed

#253 allow mapping <return> and <enter>
  autoload/ctrlspace/keys.vim
  autoload/ctrlspace/window.vim
Labels: enhancement

#261 Fix bugs of 1st March changes
  autoload/ctrlspace/util.vim
Labels: bug, fixed, neo
